[project]
name = "backup-git"
version = "1.0.0"
description = "backup all git repos inside an organisation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "python-dotenv>=1.2.1",
    "rich>=14.2.0",
]

[tool.ruff]
src = ["src"]

[tool.ruff.lint]
select = [
    "B",    # flake8-bugbear
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "C90",  # mccabe complexity
    "I",    # isort
    "ERA",  # Eradicate (commented out code)
    "A",    # flake8-builtins (overwriting python builtins)
    "PTH",  # flake8-use-pathlib
    "N",    # pep8-naming
    "D101", # pydocstyle: Missing docstring in class
    "D102", # pydocstyle: Missing docstring in method
    "D103", # pydocstyle: Missing docstring in function
]
